/**
 * CloseOS Sign — journal d'un contrat (onglet « Journal » de la fiche propriétaire).
 * Mise en forme pure des événements de sign_signature_events (testée dans tests/sign/journal.test.ts).
 */

export interface JournalEventRow {
  created_at: string;
  event_type: string;
  email: string | null;
  ip_address: string | null;
  user_agent: string | null;
  metadata: Record<string, any> | null;
}

export interface JournalLine {
  at: string;
  signerIndex: number | null;
  signer: string;
  label: string;
  tone: 'neutral' | 'success' | 'warning' | 'danger';
  ip: string;
  device: string;
}

const LABELS: Record<string, [string, string, JournalLine['tone']]> = {
  created: ['Contrat créé', 'Contract created', 'neutral'],
  sent: ['Envoyé au signataire', 'Sent to signer', 'neutral'],
  reminder: ['Relance envoyée', 'Reminder sent', 'neutral'],
  opened: ['Document ouvert', 'Document opened', 'neutral'],
  downloaded: ['Document téléchargé', 'Document downloaded', 'neutral'],
  otp_sent: ['Code de vérification envoyé', 'Verification code sent', 'neutral'],
  otp_verified: ['Code de vérification validé', 'Verification code validated', 'success'],
  email_access: ['Accès à la boîte mail prouvé', 'Mailbox access proven', 'success'],
  consent: ['Consentement donné', 'Consent given', 'neutral'],
  signed: ['Signature', 'Signed', 'success'],
  paid: ['Paiement effectué', 'Payment made', 'success'],
  completed: ['Contrat complété (toutes les signatures)', 'Contract completed (all signatures)', 'success'],
  sealed: ['Document scellé', 'Document sealed', 'success'],
  certified: ['Certificat de preuve émis', 'Proof certificate issued', 'success'],
  declined: ['Signataire bloqué', 'Signer blocked', 'danger'],
  unlocked: ['Déblocage par le propriétaire', 'Unblocked by the owner', 'warning'],
  link_renewed: ['Nouveau lien généré par le propriétaire', 'New link generated by the owner', 'warning'],
};

/** Libellé d'un événement ; les événements « security » sont précisés par leur type. */
export function journalLabel(row: Pick<JournalEventRow, 'event_type' | 'metadata'>, lang: 'fr' | 'en'): { label: string; tone: JournalLine['tone'] } {
  const fr = lang === 'fr';
  const md = row.metadata ?? {};
  if (row.event_type === 'security') {
    if (md.kind === 'verification_locked') {
      return { label: fr ? `Verrouillage après 3 échecs (étape ${md.step ?? '?'})` : `Locked after 3 failures (step ${md.step ?? '?'})`, tone: 'danger' };
    }
    if (md.kind === 'verification_failed') {
      const what = md.step === 1 ? (fr ? 'coordonnée non autorisée' : 'unauthorized contact') : (fr ? 'code erroné' : 'wrong code');
      const n = md.attempt ? (fr ? `, essai ${md.attempt}` : `, attempt ${md.attempt}`) : '';
      return { label: fr ? `Échec de vérification (${what}${n})` : `Verification failed (${what}${n})`, tone: 'warning' };
    }
    return { label: fr ? 'Événement de sécurité' : 'Security event', tone: 'warning' };
  }
  const l = LABELS[row.event_type];
  if (!l) return { label: row.event_type, tone: 'neutral' };
  let label = l[fr ? 0 : 1];
  if ((row.event_type === 'otp_sent' || row.event_type === 'otp_verified') && md.channel) {
    label += md.channel === 'sms' ? ' (SMS)' : ' (email)';
  }
  if (row.event_type === 'unlocked' || row.event_type === 'link_renewed') {
    if (md.via === 'mcp') label += fr ? ' — via le connecteur IA' : ' — via the AI connector';
    if (md.via === 'api') label += fr ? ' — via l’API' : ' — via the API';
  }
  return { label, tone: l[2] };
}

/** Navigateur et système lisibles, à partir du user-agent. */
export function deviceLabel(ua: string | null): string {
  if (!ua) return '—';
  const br = /Edg/.test(ua) ? 'Edge' : /OPR|Opera/.test(ua) ? 'Opera' : /Chrome/.test(ua) ? 'Chrome' : /Firefox/.test(ua) ? 'Firefox' : /Safari/.test(ua) ? 'Safari' : 'Navigateur';
  const os = /Windows/.test(ua) ? 'Windows' : /iPhone|iPad|iOS/.test(ua) ? 'iOS' : /Mac OS X|Macintosh/.test(ua) ? 'macOS' : /Android/.test(ua) ? 'Android' : /Linux/.test(ua) ? 'Linux' : '';
  return os ? `${br} · ${os}` : br;
}

/**
 * Lignes du journal dans l'ordre chronologique. Le signataire est résolu par metadata.signer_index
 * (nom, sinon email, sinon « Signataire N ») ; les événements de contrat n'ont pas de signataire.
 */
export function buildJournal(
  rows: JournalEventRow[],
  signers: { signerIndex: number; name?: string | null; email?: string | null }[],
  lang: 'fr' | 'en',
): JournalLine[] {
  const contractLevel = new Set(['created', 'completed', 'sealed', 'certified']);
  return [...rows]
    .sort((a, b) => a.created_at.localeCompare(b.created_at))
    .map((r) => {
      const idx = contractLevel.has(r.event_type) ? null : Number(r.metadata?.signer_index ?? 1) || 1;
      const s = idx == null ? undefined : signers.find((x) => x.signerIndex === idx);
      const who = idx == null
        ? '—'
        : s?.name?.trim() || s?.email?.trim() || r.email || (lang === 'fr' ? `Signataire ${idx}` : `Signer ${idx}`);
      const { label, tone } = journalLabel(r, lang);
      return { at: r.created_at, signerIndex: idx, signer: who, label, tone, ip: r.ip_address || '—', device: deviceLabel(r.user_agent) };
    });
}
