ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS logo_url text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS description text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS website text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS address text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS org_phone text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS org_email text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS onboarding_message text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS onboarding_video_url text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS onboarding_checklist jsonb DEFAULT '[]'::jsonb;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS raison_sociale text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS billing_address text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS billing_zip text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS billing_city text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS billing_country text DEFAULT 'France';
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS siret text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS tva_number text;
ALTER TABLE business_settings ADD COLUMN IF NOT EXISTS custom_sections jsonb DEFAULT '[]'::jsonb;
